In [1]:
import numpy as np

# DCT

In [2]:
x = np.array([50, 51, 52, 55, 56, 54, 53, 52])

In [24]:
# y(k=0)
u_0 = np.ones(8) / (2 * np.sqrt(2))
np.dot(x, u_0)

149.5530842209548

In [66]:
u_1 = np.cos((2 * np.arange(8) + 1) * np.pi * 1 / 16) / 2 # y(k=1)
u_2 = np.cos((2 * np.arange(8) + 1) * np.pi * 2 / 16) / 2 # y(k=2)
u_3 = np.cos((2 * np.arange(8) + 1) * np.pi * 3 / 16) / 2 # y(k=3)
u_4 = np.cos((2 * np.arange(8) + 1) * np.pi * 4 / 16) / 2 # y(k=4)
u_5 = np.cos((2 * np.arange(8) + 1) * np.pi * 5 / 16) / 2 # y(k=5)
u_6 = np.cos((2 * np.arange(8) + 1) * np.pi * 6 / 16) / 2 # y(k=6)
u_7 = np.cos((2 * np.arange(8) + 1) * np.pi * 7 / 16) / 2 # y(k=7)

y = np.dot(x, np.vstack([u_0, u_1, u_2, u_3, u_4, u_5, u_6, u_7]).T)
y

array([ 1.49553084e+02, -2.46537029e+00, -4.54014133e+00,  6.22191107e-01,
        1.06066017e+00, -1.85610081e-01, -7.98195913e-01,  1.94029389e-02])

In [67]:
np.isclose(np.sum(np.power(x, 2)), np.sum(np.power(y, 2)))

True

In [73]:
yc = y.copy() # Deep copy
yc[3:] = np.zeros(5)

# IDCT

In [74]:
v_0 = np.ones(8) / (2 * np.sqrt(2))
np.dot(yc, v_0), np.dot(y, v_0)

(50.398177615535, 50.65218742088154)

In [75]:
v_1 = np.cos((2 * np.arange(8) + 1) * np.pi * 1 / 16) / 2 # y(k=1)
v_2 = np.cos((2 * np.arange(8) + 1) * np.pi * 2 / 16) / 2 # y(k=2)
v_3 = np.cos((2 * np.arange(8) + 1) * np.pi * 3 / 16) / 2 # y(k=3)
v_4 = np.cos((2 * np.arange(8) + 1) * np.pi * 4 / 16) / 2 # y(k=4)
v_5 = np.cos((2 * np.arange(8) + 1) * np.pi * 5 / 16) / 2 # y(k=5)
v_6 = np.cos((2 * np.arange(8) + 1) * np.pi * 6 / 16) / 2 # y(k=6)
v_7 = np.cos((2 * np.arange(8) + 1) * np.pi * 7 / 16) / 2 # y(k=7)

xc_hat = np.dot(yc, np.vstack([v_0, v_1, v_2, v_3, v_4, v_5, v_6, v_7]).T)
x_hat = np.dot(y, np.vstack([v_0, v_1, v_2, v_3, v_4, v_5, v_6, v_7]).T)

In [81]:
np.sum(np.power(xc_hat - x_hat, 2))

2.1840660650320953

In [82]:
xc_hat

array([50.39817762, 71.0536079 , 69.48150702, 64.64135931, 55.35182238,
       42.30975155, 27.65732455, 13.38552808])

# Synthesis

In [86]:
amps = np.array([0.6, 0.25, 0.1, 0.05])
fs = [100, 200, 300, 400]
framerate = 11025

def synthesize(amps, fs, ts): 
    args = np.outer(ts, fs)
    M = np.cos(2 * np.pi * args)
    ys = np.dot(M, amps)
    return ys

ts = np.linspace(0, 1, framerate)
ys = synthesize(amps, fs, ts)
len(ys)

11025

# Analysis

In [89]:
def analyze(ys, fs, ts):
    args = np.outer(ts, fs)
    M = np.cos(2 * np.pi * args)
    amps = np.linalg.solve(M, ys)
    return amps

n = len(fs)
amps2 = analyze(ys[:n], fs, ts[:n])
amps2

array([0.6 , 0.25, 0.1 , 0.05])